version: '3.8'

services:
  kai-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # If you want to use a reverse proxy like nginx
    # networks:
    #   - web 